### ISSUE TITLE
safe to use?

### ISSUE THREAD

**Issue by enesahn** [WincerChan/SolVanityCL#20]
Is it safe to use it? Can I use the created wallet as my main wallet?

**Comment by Vickynicole** [comment]
Hello @enesahn 
Using a wallet as your main one depends on its security and trustworthiness. If the created wallet has strong security features and you trust the platform, it could be safe.

**Comment by enesahn** [comment]
> Hello @enesahn Using a wallet as your main one depends on its security and trustworthiness. If the created wallet has strong security features and you trust the platform, it could be safe.

I mean. Generated wallets are safe right? Can another person generate my exact pubkey/wallet? What are the chances of that?

**Comment by Vickynicole** [comment]
Hello @enesahn 
Yes, generated wallets are generally safe. The chances of another person generating the exact same public key or wallet are astronomically low due to the vast number of possible key combinations. The security relies on the randomness and complexity of the key generation process, making it practically impossible for someone else to create the same wallet. So, you can feel confident using a generated wallet.

**Comment by WincerChan** [comment]
The [initial private key](https://github.com/WincerChan/SolVanityCL/blob/master/main.py#L36) in this tool is generated using Python’s secrets.token_bytes, which provides cryptographically secure randomness. It relies on the operating system’s secure random number generator (e.g., /dev/urandom on Linux or CryptGenRandom on Windows), ensuring unpredictability. 
With 2^{256} possible private keys, the chance of someone else generating the same private key is astronomically low, effectively zero. As long as the private key is kept secure, the generated wallets are safe to use and unique.
